#!/usr/bin/env python3.14
"""RFC 116 stage 3 (D4, D4a, D7): generate .github/workflows/ci.yml.

The committed workflow is a *generation*, checked like `cargo fmt --check`:

    python3.14 scripts/generate-ci-workflow.py --root . --check    # CI, and you
    python3.14 scripts/generate-ci-workflow.py --root . --write    # to update it

Inputs (D4 says what they are, because "generated from the table" alone was
false: the table holds no lane-to-setup mapping, no triggers and no rationale):

  ci/gate-inputs.toml         [runner], [tools], [rust_components], [actions],
                              [gates], [gate_matrix_exceptions] and the new
                              [lane_profiles]: what each lane needs from a runner.
  ci/workflow-template.toml   the parts that are text, not facts: the header, the
                              per-lane rationale comments, and the jobs that are
                              not a lane's `checkout + dispatcher` shape (G12's
                              job, `gate-inputs`, `gate-matrix-fixtures`).

What this holds that nothing held before (the hole D4a names): the tool versions
in `[tools]` are no longer compared to a workflow after the fact; they are the
workflow. And each lane's `+toolchain` in its `[gates]` command must agree with
its profile and with `[tools]`, so bumping the MSRV in one place and not the
others fails here instead of passing.

`[gates]` is not read for its *shape* and is never rewritten: values are single
lines, which `scripts/ci-gate.sh`'s awk requires (D7). This script only reads it.

Template placeholders, expanded in the header, lane comments and raw jobs:

  @@uses.<key>@@              `actions/<repo>@<sha> # vN` from [actions]
  @@runner.label@@            [runner] label
  @@runner.system_packages@@  the packages, space-separated
  @@runner.bash_minimum@@ / bash_maximum_exclusive / bash_major / bash_minor
  @@tools.<key>@@             [tools] value

A raw block may not spell a runner label, an action SHA, a toolchain or a tool
version out: that is the drift this exists to prevent, so it is a violation.

Exit 0 = the file is a fresh generation (or was written). Exit 1 = it is not, or
the inputs do not agree; each cause is on stderr. Exit 2 = an input cannot be read.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from pathlib import Path

WORKFLOW = Path(".github/workflows/ci.yml")
MANIFEST = Path("ci/gate-inputs.toml")
TEMPLATE = Path("ci/workflow-template.toml")

GENERATED_NOTICE = (
    "# GENERATED by scripts/generate-ci-workflow.py from ci/gate-inputs.toml and\n"
    "# ci/workflow-template.toml (RFC 116 stage 3). Do not edit this file: edit those,\n"
    "# then run `python3.14 scripts/generate-ci-workflow.py --root . --write`.\n"
    "# CI fails when this file is not a fresh generation.\n"
)

ACTION_REPOS = {
    "checkout": "actions/checkout",
    "cache": "actions/cache",
    "upload_artifact": "actions/upload-artifact",
    "rust_toolchain": "dtolnay/rust-toolchain",
    "setup_python": "actions/setup-python",
}
PROFILE_KEYS = {"title", "setup", "toolchain", "apt", "cache", "mdbook", "tz", "fetch_depth", "job"}
TOOLS = ("rust_msrv", "rust_stable", "mdbook", "python")

# What a raw block (or a comment) must not spell out itself.
LITERALS = (
    (re.compile(r"runs-on:\s*(?!@@)\S"), "a literal runner label; use @@runner.label@@"),
    (re.compile(r"@[0-9a-f]{40}"), "a literal action SHA; use @@uses.<key>@@"),
    (re.compile(r"\buses:\s*(?!@@)\S"), "a literal `uses:`; use @@uses.<key>@@"),
    (re.compile(r'toolchain:\s*(?!"?@@)\S'), "a literal toolchain; use @@tools.rust_msrv@@ or @@tools.rust_stable@@"),
    (re.compile(r'python-version:\s*(?!"?@@)\S'), "a literal Python version; use @@tools.python@@"),
    (re.compile(r"mdbook --version\s+(?!@@)\S"), "a literal mdBook version; use @@tools.mdbook@@"),
)


class Inputs:
    def __init__(self, root: Path) -> None:
        self.root = root
        with (root / MANIFEST).open("rb") as h:
            self.manifest = tomllib.load(h)
        with (root / TEMPLATE).open("rb") as h:
            self.template = tomllib.load(h)
        self.failures: list[str] = []
        self.tools_used: set[str] = set()

    def fail(self, msg: str) -> None:
        self.failures.append(msg)


def natural(lane: str) -> tuple[int, str]:
    m = re.fullmatch(r"G(\d+)([a-z]?)", lane)
    return (int(m.group(1)), m.group(2)) if m else (10**6, lane)


def expand(text: str, inp: Inputs, where: str) -> str:
    m = inp.manifest
    runner, tools, actions = m["runner"], m["tools"], m["actions"]

    def sub(match: re.Match[str]) -> str:
        key = match.group(1)
        kind, _, name = key.partition(".")
        if kind == "uses":
            if name not in actions:
                inp.fail(f"{where}: @@{key}@@ names no [actions] entry")
                return match.group(0)
            repo = next((r for prefix, r in ACTION_REPOS.items() if name.startswith(prefix)), None)
            if repo is None:
                inp.fail(f"{where}: @@{key}@@: no repository is known for [actions] key {name}")
                return match.group(0)
            version = re.search(r"_v(\d+)$", name)
            return f"{repo}@{actions[name]}" + (f" # v{version.group(1)}" if version else "")
        if kind == "tools" and name in tools:
            inp.tools_used.add(name)
            return str(tools[name])
        if kind == "runner":
            if name == "label":
                return runner["label"]
            if name == "system_packages":
                return " ".join(runner["system_packages"])
            if name in ("bash_minimum", "bash_maximum_exclusive"):
                return runner[name]
            if name == "bash_major":
                return runner["bash_minimum"].split(".")[0]
            if name == "bash_minor":
                return runner["bash_minimum"].split(".")[1]
        inp.fail(f"{where}: unknown placeholder @@{key}@@")
        return match.group(0)

    return re.sub(r"@@([a-z_.0-9A-Z-]+)@@", sub, text)


def lint_raw(text: str, where: str, inp: Inputs) -> None:
    for pattern, what in LITERALS:
        for n, line in enumerate(text.split("\n"), start=1):
            if line.lstrip().startswith("#"):
                continue
            if pattern.search(line):
                inp.fail(f"{where}, line {n}: {what}: {line.strip()!r}")


def indent(block: str, prefix: str) -> str:
    return "\n".join(prefix + l if l else l for l in block.strip("\n").split("\n"))


def strip_nl(text: str) -> str:
    return text[:-1] if text.endswith("\n") else text


# ── lane jobs ───────────────────────────────────────────────────────────


def uses(inp: Inputs, key: str) -> str:
    return expand(f"@@uses.{key}@@", inp, "lane job")


def lane_job(lane: str, prof: dict, inp: Inputs) -> str:
    m = inp.manifest
    runner, tools = m["runner"], m["tools"]
    where = f"[lane_profiles] {lane}"
    for key in prof:
        if key not in PROFILE_KEYS:
            inp.fail(f"{where}: unknown key `{key}`")
    setup = prof.get("setup")
    if setup not in ("rust", "python", "none"):
        inp.fail(f"{where}: `setup` must be rust, python or none")
    title = prof.get("title", "")
    if not title:
        inp.fail(f"{where}: no `title`")
    for t in TOOLS:
        if "{" + t + "}" in title:
            inp.tools_used.add(t)
    try:
        title = title.format(**{t: tools[t] for t in TOOLS})
    except (KeyError, IndexError) as err:
        inp.fail(f"{where}: `title` names an unknown placeholder {err}")

    out = [f"  {lane}:"]
    comment = inp.template.get("lane_comments", {}).get(lane)
    if comment:
        out.append(strip_nl(comment))
    out += [
        f'    name: "{lane} — {title}"',
        f"    runs-on: {runner['label']}",
        "    steps:",
        f"      - uses: {uses(inp, 'checkout_v6')}",
    ]
    if "fetch_depth" in prof:
        out += ["        with:", f"          fetch-depth: {prof['fetch_depth']}"]

    command = m["gates"].get(lane, "")
    if setup == "rust":
        tc = prof.get("toolchain")
        if tc not in ("msrv", "stable"):
            inp.fail(f"{where}: rust lanes need toolchain = msrv or stable")
            tc = "stable"
        version = tools["rust_msrv"] if tc == "msrv" else tools["rust_stable"]
        inp.tools_used.add("rust_msrv" if tc == "msrv" else "rust_stable")
        components = m.get("rust_components", {}).get(lane, [])
        if prof.get("apt"):
            out += [
                "      - name: Install system deps",
                "        run: |",
                "          sudo apt-get update",
                f"          sudo apt-get install -y {' '.join(runner['system_packages'])}",
            ]
        out += [
            f"      - name: Install Rust {version}",
            f"        uses: {uses(inp, 'rust_toolchain_stable')}",
            "        with:",
            f'          toolchain: "{version}"' if tc == "msrv" else f"          toolchain: {version}",
        ]
        if components:
            out.append(f"          components: {', '.join(components)}")
        if prof.get("cache"):
            out += cache_step(inp)
        if prof.get("mdbook"):
            inp.tools_used.add("mdbook")
            out.append(f"      - name: Install mdBook {tools['mdbook']}")
            note = inp.template.get("snippets", {}).get("mdbook_step_comment")
            if note:
                out.append(indent(note, "        "))
            out.append(f"        run: cargo install mdbook --version {tools['mdbook']} --locked")
        check_toolchain(lane, command, version, tc, inp)
    elif setup == "python":
        inp.tools_used.add("python")
        out += [
            f"      - name: Install Python {tools['python']}",
            f"        uses: {uses(inp, 'setup_python_v7')}",
            "        with:",
            f'          python-version: "{tools["python"]}"',
        ]
        for found in re.findall(r"\bpython(3\.\d+)\b", command):
            if found != tools["python"]:
                inp.fail(
                    f"{where}: the command runs python{found}, but [tools] python is {tools['python']}"
                )
    out += [f"      - name: {lane}", f"        run: bash scripts/ci-gate.sh {lane}"]
    if "tz" in prof:
        out.append("        env:")
        note = inp.template.get("lane_env_comments", {}).get(lane)
        if note:
            out.append(indent(note, "          "))
        out.append(f"          TZ: {prof['tz']}")
    return "\n".join(out)


def cache_step(inp: Inputs) -> list[str]:
    return [
        "      - name: Cache cargo registry",
        f"        uses: {uses(inp, 'cache_v5')}",
        "        with:",
        "          path: |",
        "            ~/.cargo/registry",
        "            ~/.cargo/git",
        "          key: ${{ runner.os }}-gate-input-v1-cargo-${{ hashFiles('**/Cargo.lock') }}",
        "          restore-keys: |",
        "            ${{ runner.os }}-cargo-",
    ]


def check_toolchain(lane: str, command: str, version: str, tc: str, inp: Inputs) -> None:
    """The hole D4a names: a `+toolchain` in a command that disagrees with the
    profile and [tools]."""
    for found in re.findall(r"\bcargo \+(\S+)", command):
        if found != version:
            inp.fail(
                f"[gates] {lane}: the command runs `cargo +{found}`, but its profile says "
                f"toolchain = {tc} and [tools] says {version}"
            )


# ── the round trip ──────────────────────────────────────────────────────


def check_lane_set(inp: Inputs) -> None:
    m = inp.manifest
    lanes = set(m.get("gates", {})) | set(m.get("gate_matrix_exceptions", {}))
    profiles = m.get("lane_profiles", {})
    for lane in sorted(lanes - set(profiles), key=natural):
        inp.fail(f"lane {lane} is in [gates] or [gate_matrix_exceptions] but has no [lane_profiles] entry, so it would have no job")
    for lane in sorted(set(profiles) - lanes, key=natural):
        inp.fail(f"[lane_profiles] has {lane}, which is neither a [gates] lane nor a [gate_matrix_exceptions] lane")
    # [rust_components]: exactly the cargo lanes, and each carries what its command uses.
    cargo_lanes = {
        lane
        for lane, p in profiles.items()
        if p.get("setup") == "rust" and "cargo +" in m.get("gates", {}).get(lane, "")
    }
    comps = m.get("rust_components", {})
    for lane in sorted(cargo_lanes - set(comps), key=natural):
        inp.fail(f"[rust_components] is missing {lane}")
    for lane in sorted(set(comps) - cargo_lanes, key=natural):
        inp.fail(f"[rust_components] has {lane}, which is not a cargo lane")
    for lane in sorted(cargo_lanes & set(comps), key=natural):
        cmd = m["gates"][lane]
        want = []
        if re.search(r"\bcargo \+\S+ clippy\b", cmd):
            want.append("clippy")
        if re.search(r"\bcargo \+\S+ fmt\b", cmd):
            want.append("rustfmt")
        if sorted(comps[lane]) != sorted(want):
            inp.fail(
                f"[rust_components] {lane} = {comps[lane]}, but its command needs {want}"
            )
    if m.get("version") != 1 or m.get("gate_matrix_version") != 1:
        inp.fail("version and gate_matrix_version must both be 1")


def render(inp: Inputs) -> str:
    m, t = inp.manifest, inp.template
    check_lane_set(inp)
    profiles = m.get("lane_profiles", {})
    jobs: list[str] = []
    for lane in sorted(profiles, key=natural):
        prof = profiles[lane]
        if "job" in prof:
            block = t.get("lane_jobs", {}).get(prof["job"])
            if block is None:
                inp.fail(f"[lane_profiles] {lane}: job {prof['job']!r} is not in [lane_jobs]")
                continue
            lint_raw(block, f"[lane_jobs] {prof['job']}", inp)
            jobs.append(expand(strip_nl(block), inp, f"[lane_jobs] {prof['job']}"))
        else:
            jobs.append(lane_job(lane, prof, inp))
    for name, block in t.get("extra_jobs", {}).items():
        lint_raw(block, f"[extra_jobs] {name}", inp)
        jobs.append(expand(strip_nl(block), inp, f"[extra_jobs] {name}"))
    for lane, comment in t.get("lane_comments", {}).items():
        if lane not in profiles:
            inp.fail(f"[lane_comments] {lane}: no such lane profile")
    header = t.get("header", "")
    lint_raw(header, "header", inp)
    lint_raw("\n".join(t.get("lane_comments", {}).values()), "[lane_comments]", inp)
    text = GENERATED_NOTICE + expand(strip_nl(header), inp, "header") + "\n" + "\n\n".join(jobs) + "\n"
    # A [tools] entry nothing in the workflow uses is a pin nothing reads.
    for tool in TOOLS:
        if tool in m.get("tools", {}) and tool not in inp.tools_used:
            inp.fail(f"[tools] {tool} is declared but nothing in the generated workflow uses it")
    return text


def job_keys(text: str) -> list[str]:
    in_jobs, keys = False, []
    for line in text.split("\n"):
        if line == "jobs:":
            in_jobs = True
            continue
        if in_jobs:
            m = re.fullmatch(r"  ([A-Za-z0-9_-]+):", line)
            if m:
                keys.append(m.group(1))
    return keys


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail unless the committed workflow is a fresh generation")
    mode.add_argument("--write", action="store_true", help="write the generation over the committed workflow")
    args = parser.parse_args(argv)

    root = Path(args.root)
    try:
        inp = Inputs(root)
    except (OSError, tomllib.TOMLDecodeError) as err:
        print(f"generate-ci-workflow: cannot read an input: {err}", file=sys.stderr)
        return 2

    generated = render(inp)
    if inp.failures:
        for f in inp.failures:
            print(f"generate-ci-workflow: {f}", file=sys.stderr)
        print(f"generate-ci-workflow: failed with {len(inp.failures)} violation(s)", file=sys.stderr)
        return 1

    target = root / WORKFLOW
    if args.write:
        target.write_text(generated, encoding="utf-8")
        print(f"generate-ci-workflow: wrote {WORKFLOW} ({len(job_keys(generated))} jobs)")
        return 0

    try:
        committed = target.read_text(encoding="utf-8")
    except OSError as err:
        print(f"generate-ci-workflow: cannot read {WORKFLOW}: {err}", file=sys.stderr)
        return 2
    if committed == generated:
        print(f"generate-ci-workflow: {WORKFLOW} is a fresh generation ({len(job_keys(generated))} jobs)")
        return 0

    want, have = job_keys(generated), job_keys(committed)
    for job in [j for j in want if j not in have]:
        print(f"generate-ci-workflow: job {job} is generated but missing from {WORKFLOW}", file=sys.stderr)
    for job in [j for j in have if j not in want]:
        print(
            f"generate-ci-workflow: job {job} is in {WORKFLOW} but no table entry generates it",
            file=sys.stderr,
        )
    diff = list(
        difflib.unified_diff(
            committed.split("\n"), generated.split("\n"), f"{WORKFLOW} (committed)", f"{WORKFLOW} (generated)", lineterm=""
        )
    )
    for line in diff[:60]:
        print(line, file=sys.stderr)
    if len(diff) > 60:
        print(f"... {len(diff) - 60} more diff lines", file=sys.stderr)
    print(
        f"generate-ci-workflow: {WORKFLOW} is not a fresh generation; run "
        "`python3.14 scripts/generate-ci-workflow.py --root . --write` and commit the result",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
